### ISSUE TITLE
ability to fulfill template `setup.py` parameters

### ISSUE THREAD

**Issue by AHReccese** [openscilab/reserver#12]
#### Description
- description
- author
- author email
- URL
- download URL
- source
- license

**Comment by AHReccese** [comment]
Since it is too fine-grained edition, I think it is better to just have it in Python usage (and not in the CLI usage).
By passing a dictionary that contains the fulfillment of the above attributes.
Do you agree? let me know so I can plan this out.
@sepandhaghighi

**Comment by sepandhaghighi** [comment]
I believe this issue can be easily handled by using a `JSON` file in CLI mode.
In Python, converting `JSON` to a dictionary and vice versa is very straightforward.

**Comment by AHReccese** [comment]
OK, I will do this. why not.
but using only one config file when reserving a batch of names right?
@sepandhaghighi

**Comment by AHReccese** [comment]
Answer: Either one config file or per name config file.
