### ISSUE TITLE
CLI Handler

### ISSUE THREAD

**Issue by AHReccese** [openscilab/reserver#13]
#### Description
Add CLI options

```shell
reserver --name sample_name1 sample_name2 sample_name3 --token=PYPI_TOKEN --test
```

**Comment by AHReccese** [comment]
@sadrasabouri @sepandhaghighi 
Hey guys, let me know your comments on the suggested CLI.
also if you have a better idea, please surely let me know, I'm a little bit worried to get PyPI token in the command line(which will be recorded in the bash history)

**Comment by sadrasabouri** [comment]
> @sadrasabouri @sepandhaghighi Hey guys, let me know your comments on the suggested CLI. also if you have a better idea, please surely let me know, I'm a little bit worried to get PyPI token in the command line(which will be recorded in the bash history)

I had two suggestions:
- `--test` is enough as a true/false flag, no need for `--test=True`
- Regarding Pypi token, I think it's OK as is. We can also check from user's environment variables.

**Comment by AHReccese** [comment]
@sadrasabouri Thank you for your comment, I will consider both.

**Comment by sepandhaghighi** [comment]
@AHReccese 
I understand your concern about the Pypi token in CLI mode, but I don't think it makes sense to use an environmental variable in the CLI! Therefore, I suggest using `--token` and printing a warning message about it.

My suggestion:

```shell
reserver --name="sample_name1,sample_name2,sample_name3,..." --token=PYPI_TOKEN --test
```
